import { useMemo, useState } from "react";
import { CheckCircle2, Clock3, Heart, ImagePlus, Share2, Sparkles, Upload, XCircle } from "lucide-react";

const seed = [
  { id:"seed-1", name:"Sunrise at the Taj", user:"@aanya.travels", image:"/images/tajmahal.webp", text:"The marble changes character every few minutes.", status:"approved" },
  { id:"seed-2", name:"Old lanes of Kashi", user:"@rohanexplores", image:"/images/kashi.webp", text:"Found a tiny weaving workshop hidden behind the market.", status:"approved" },
  { id:"seed-3", name:"Colours of Mithila", user:"@meghna", image:"/images/culture/art-storytelling/madhubani.webp", text:"Met an artist and learned why every border matters.", status:"approved" },
];
const key="aarambh-community-submissions";
export default function Community(){
 const [posts,setPosts]=useState(()=>{try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return []}});
 const [form,setForm]=useState({title:"",story:"",location:"",category:"Heritage",image:""});
 const [notice,setNotice]=useState(false); const [liked,setLiked]=useState({});
 const [admin,setAdmin]=useState(false);
 const submissions=useMemo(()=>[...posts], [posts]);
 const save=(next)=>{setPosts(next);localStorage.setItem(key,JSON.stringify(next));};
 const submit=e=>{e.preventDefault(); if(!form.title.trim()||!form.story.trim()) return; const item={...form,id:crypto.randomUUID?.()||String(Date.now()),user:"@you",status:"pending",createdAt:new Date().toISOString()}; save([item,...posts]);setForm({title:"",story:"",location:"",category:"Heritage",image:""});setNotice(true);};
 const image=e=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>setForm(f=>({...f,image:String(r.result)}));r.readAsDataURL(file)};
 const moderate=(id,status)=>save(posts.map(p=>p.id===id?{...p,status}:p));
 const publicPosts=[...seed,...posts.filter(p=>p.status==="approved")];
 return <main className="living-page community-page">
  <section className="living-hero community-hero"><div className="living-hero-copy"><span className="living-kicker"><Sparkles size={15}/> COMMUNITY OF EXPLORERS</span><h1>See India through<br/><em>other people's eyes.</em></h1><p>Share a story, photograph or cultural discovery. Every new contribution is reviewed before it becomes public.</p><button className="upload-discovery community-upload" onClick={()=>document.getElementById("community-form")?.scrollIntoView({behavior:"smooth"})}><Upload size={18}/> Share your discovery</button></div><div className="living-hero-art"><img src="/images/crafts/folk-art/madhubani.webp" alt="Community discovery"/><div className="hero-art-card"><span>{publicPosts.length}</span><div><small>SHARED NOW</small><strong>Discoveries from travellers</strong></div></div></div></section>
  <section className="living-section" id="community-form"><div className="living-heading"><div><span>01 · CONTRIBUTE</span><h2>Tell the community what you found.</h2></div><p>Stories are saved as pending until a demo admin approves them.</p></div>
   <form className="community-form" onSubmit={submit}><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required placeholder="A memorable discovery"/></label><label>Story<textarea value={form.story} onChange={e=>setForm({...form,story:e.target.value})} required placeholder="What did you see, learn or experience?"/></label><div className="form-row"><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="City / region"/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Heritage</option><option>Culture</option><option>Food</option><option>Crafts</option><option>Hidden Gem</option></select></label></div><label className="photo-picker"><ImagePlus size={18}/> {form.image?"Photo selected":"Add a photo"}<input type="file" accept="image/*" onChange={image}/></label><button type="submit" className="primary-action">Submit for Admin Approval</button></form>
  </section>
  <section className="living-section"><div className="living-heading"><div><span>02 · COMMUNITY FEED</span><h2>Small moments. Big stories.</h2></div><p>Only approved contributions appear in this public feed.</p></div><div className="discovery-grid community-discovery-grid">{publicPosts.map((post,index)=><article className="discovery-card" key={post.id||index}><img src={post.image||"/images/placeholder.svg"} alt={post.title||post.name||"Community story"} loading="lazy" onError={e=>{e.currentTarget.src="/images/placeholder.svg"}}/><div className="discovery-overlay"><div><span>{post.user}</span><h3>{post.title||post.name}</h3><p>{post.text||post.story}</p></div><div className="discovery-actions"><button aria-label="Like" onClick={()=>setLiked(p=>({...p,[index]:!p[index]}))} className={liked[index]?"liked":""}><Heart size={17} fill={liked[index]?"currentColor":"none"}/></button><button aria-label="Share"><Share2 size={17}/></button></div></div></article>)}</div></section>
  <section className="living-section moderation-section"><div className="moderation-head"><div><span>03 · DEMO MODERATION</span><h2>Admin approval desk</h2></div><button onClick={()=>setAdmin(v=>!v)}>{admin?"Hide":"Open"} moderation</button></div>{admin&&<div className="moderation-list">{submissions.length===0?<div className="empty-state">No pending submissions yet.</div>:submissions.map(p=><article className="moderation-card" key={p.id}><div>{p.image&&<img src={p.image} alt="Submission preview"/>}<div><strong>{p.title}</strong><p>{p.story}</p><small>{p.location||"Location not provided"} · {p.category} · <b>{p.status.toUpperCase()}</b></small></div></div><div className="moderation-actions">{p.status==="pending"&&<><button onClick={()=>moderate(p.id,"approved")}><CheckCircle2 size={16}/> Approve</button><button onClick={()=>moderate(p.id,"rejected")}><XCircle size={16}/> Reject</button></>}{p.status!=="pending"&&<span className={`status-pill ${p.status}`}><Clock3 size={14}/> {p.status}</span>}</div></article>)}</div>}</section>
  {notice&&<div className="approval-modal" role="dialog" aria-modal="true"><div className="approval-box"><button className="modal-close" aria-label="Close" onClick={()=>setNotice(false)}>×</button><CheckCircle2 size={42}/><h3>Waiting for Admin Approval</h3><p>Your contribution has been submitted successfully. It is currently waiting for admin approval. Once approved, it will appear in the Community section.</p><button onClick={()=>setNotice(false)}>Got it</button></div></div>}
 </main>
}
